/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdressesRouteImport } from './routes/adresses'
import { Route as DashboardTravauxRouteImport } from './routes/dashboard-travaux'
import { Route as FournisseursRouteImport } from './routes/fournisseurs'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ImportPspRouteImport } from './routes/import-psp'
import { Route as ImportTravauxRouteImport } from './routes/import-travaux'
import { Route as PreparationPspRouteImport } from './routes/preparation-psp'
import { Route as PspValidationRouteImport } from './routes/psp-validation'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as FournisseursIndexRouteImport } from './routes/fournisseurs.index'
import { Route as FournisseursFournisseurIdRouteImport } from './routes/fournisseurs.$fournisseurId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdressesRoute = AdressesRouteImport.update({
  id: '/adresses',
  path: '/adresses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTravauxRoute = DashboardTravauxRouteImport.update({
  id: '/dashboard-travaux',
  path: '/dashboard-travaux',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursRoute = FournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportPspRoute = ImportPspRouteImport.update({
  id: '/import-psp',
  path: '/import-psp',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportTravauxRoute = ImportTravauxRouteImport.update({
  id: '/import-travaux',
  path: '/import-travaux',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparationPspRoute = PreparationPspRouteImport.update({
  id: '/preparation-psp',
  path: '/preparation-psp',
  getParentRoute: () => rootRouteImport,
} as any)
const PspValidationRoute = PspValidationRouteImport.update({
  id: '/psp-validation',
  path: '/psp-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursIndexRoute = FournisseursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FournisseursRoute,
} as any)
const FournisseursFournisseurIdRoute =
  FournisseursFournisseurIdRouteImport.update({
    id: '/$fournisseurId',
    path: '/$fournisseurId',
    getParentRoute: () => FournisseursRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adresses': typeof AdressesRoute
  '/dashboard-travaux': typeof DashboardTravauxRoute
  '/fournisseurs': typeof FournisseursRouteWithChildren
  '/import': typeof ImportRoute
  '/import-psp': typeof ImportPspRoute
  '/import-travaux': typeof ImportTravauxRoute
  '/preparation-psp': typeof PreparationPspRoute
  '/psp-validation': typeof PspValidationRoute
  '/suivi': typeof SuiviRoute
  '/fournisseurs/$fournisseurId': typeof FournisseursFournisseurIdRoute
  '/fournisseurs/': typeof FournisseursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adresses': typeof AdressesRoute
  '/dashboard-travaux': typeof DashboardTravauxRoute
  '/import': typeof ImportRoute
  '/import-psp': typeof ImportPspRoute
  '/import-travaux': typeof ImportTravauxRoute
  '/preparation-psp': typeof PreparationPspRoute
  '/psp-validation': typeof PspValidationRoute
  '/suivi': typeof SuiviRoute
  '/fournisseurs/$fournisseurId': typeof FournisseursFournisseurIdRoute
  '/fournisseurs': typeof FournisseursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adresses': typeof AdressesRoute
  '/dashboard-travaux': typeof DashboardTravauxRoute
  '/fournisseurs': typeof FournisseursRouteWithChildren
  '/import': typeof ImportRoute
  '/import-psp': typeof ImportPspRoute
  '/import-travaux': typeof ImportTravauxRoute
  '/preparation-psp': typeof PreparationPspRoute
  '/psp-validation': typeof PspValidationRoute
  '/suivi': typeof SuiviRoute
  '/fournisseurs/$fournisseurId': typeof FournisseursFournisseurIdRoute
  '/fournisseurs/': typeof FournisseursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adresses'
    | '/dashboard-travaux'
    | '/fournisseurs'
    | '/import'
    | '/import-psp'
    | '/import-travaux'
    | '/preparation-psp'
    | '/psp-validation'
    | '/suivi'
    | '/fournisseurs/$fournisseurId'
    | '/fournisseurs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adresses'
    | '/dashboard-travaux'
    | '/import'
    | '/import-psp'
    | '/import-travaux'
    | '/preparation-psp'
    | '/psp-validation'
    | '/suivi'
    | '/fournisseurs/$fournisseurId'
    | '/fournisseurs'
  id:
    | '__root__'
    | '/'
    | '/adresses'
    | '/dashboard-travaux'
    | '/fournisseurs'
    | '/import'
    | '/import-psp'
    | '/import-travaux'
    | '/preparation-psp'
    | '/psp-validation'
    | '/suivi'
    | '/fournisseurs/$fournisseurId'
    | '/fournisseurs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdressesRoute: typeof AdressesRoute
  DashboardTravauxRoute: typeof DashboardTravauxRoute
  FournisseursRoute: typeof FournisseursRouteWithChildren
  ImportRoute: typeof ImportRoute
  ImportPspRoute: typeof ImportPspRoute
  ImportTravauxRoute: typeof ImportTravauxRoute
  PreparationPspRoute: typeof PreparationPspRoute
  PspValidationRoute: typeof PspValidationRoute
  SuiviRoute: typeof SuiviRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adresses': {
      id: '/adresses'
      path: '/adresses'
      fullPath: '/adresses'
      preLoaderRoute: typeof AdressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-travaux': {
      id: '/dashboard-travaux'
      path: '/dashboard-travaux'
      fullPath: '/dashboard-travaux'
      preLoaderRoute: typeof DashboardTravauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs': {
      id: '/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof FournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-psp': {
      id: '/import-psp'
      path: '/import-psp'
      fullPath: '/import-psp'
      preLoaderRoute: typeof ImportPspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-travaux': {
      id: '/import-travaux'
      path: '/import-travaux'
      fullPath: '/import-travaux'
      preLoaderRoute: typeof ImportTravauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation-psp': {
      id: '/preparation-psp'
      path: '/preparation-psp'
      fullPath: '/preparation-psp'
      preLoaderRoute: typeof PreparationPspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psp-validation': {
      id: '/psp-validation'
      path: '/psp-validation'
      fullPath: '/psp-validation'
      preLoaderRoute: typeof PspValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs/': {
      id: '/fournisseurs/'
      path: '/'
      fullPath: '/fournisseurs/'
      preLoaderRoute: typeof FournisseursIndexRouteImport
      parentRoute: typeof FournisseursRoute
    }
    '/fournisseurs/$fournisseurId': {
      id: '/fournisseurs/$fournisseurId'
      path: '/$fournisseurId'
      fullPath: '/fournisseurs/$fournisseurId'
      preLoaderRoute: typeof FournisseursFournisseurIdRouteImport
      parentRoute: typeof FournisseursRoute
    }
  }
}

interface FournisseursRouteChildren {
  FournisseursFournisseurIdRoute: typeof FournisseursFournisseurIdRoute
  FournisseursIndexRoute: typeof FournisseursIndexRoute
}

const FournisseursRouteChildren: FournisseursRouteChildren = {
  FournisseursFournisseurIdRoute: FournisseursFournisseurIdRoute,
  FournisseursIndexRoute: FournisseursIndexRoute,
}

const FournisseursRouteWithChildren = FournisseursRoute._addFileChildren(
  FournisseursRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdressesRoute: AdressesRoute,
  DashboardTravauxRoute: DashboardTravauxRoute,
  FournisseursRoute: FournisseursRouteWithChildren,
  ImportRoute: ImportRoute,
  ImportPspRoute: ImportPspRoute,
  ImportTravauxRoute: ImportTravauxRoute,
  PreparationPspRoute: PreparationPspRoute,
  PspValidationRoute: PspValidationRoute,
  SuiviRoute: SuiviRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
