/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdressesRouteImport } from './routes/adresses'
import { Route as DashboardTravauxRouteImport } from './routes/dashboard-travaux'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ImportPspRouteImport } from './routes/import-psp'
import { Route as ImportTravauxRouteImport } from './routes/import-travaux'
import { Route as PspValidationRouteImport } from './routes/psp-validation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdressesRoute = AdressesRouteImport.update({
  id: '/adresses',
  path: '/adresses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTravauxRoute = DashboardTravauxRouteImport.update({
  id: '/dashboard-travaux',
  path: '/dashboard-travaux',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportPspRoute = ImportPspRouteImport.update({
  id: '/import-psp',
  path: '/import-psp',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportTravauxRoute = ImportTravauxRouteImport.update({
  id: '/import-travaux',
  path: '/import-travaux',
  getParentRoute: () => rootRouteImport,
} as any)
const PspValidationRoute = PspValidationRouteImport.update({
  id: '/psp-validation',
  path: '/psp-validation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adresses': typeof AdressesRoute
  '/dashboard-travaux': typeof DashboardTravauxRoute
  '/import': typeof ImportRoute
  '/import-psp': typeof ImportPspRoute
  '/import-travaux': typeof ImportTravauxRoute
  '/psp-validation': typeof PspValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adresses': typeof AdressesRoute
  '/dashboard-travaux': typeof DashboardTravauxRoute
  '/import': typeof ImportRoute
  '/import-psp': typeof ImportPspRoute
  '/import-travaux': typeof ImportTravauxRoute
  '/psp-validation': typeof PspValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adresses': typeof AdressesRoute
  '/dashboard-travaux': typeof DashboardTravauxRoute
  '/import': typeof ImportRoute
  '/import-psp': typeof ImportPspRoute
  '/import-travaux': typeof ImportTravauxRoute
  '/psp-validation': typeof PspValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adresses'
    | '/dashboard-travaux'
    | '/import'
    | '/import-psp'
    | '/import-travaux'
    | '/psp-validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adresses'
    | '/dashboard-travaux'
    | '/import'
    | '/import-psp'
    | '/import-travaux'
    | '/psp-validation'
  id:
    | '__root__'
    | '/'
    | '/adresses'
    | '/dashboard-travaux'
    | '/import'
    | '/import-psp'
    | '/import-travaux'
    | '/psp-validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdressesRoute: typeof AdressesRoute
  DashboardTravauxRoute: typeof DashboardTravauxRoute
  ImportRoute: typeof ImportRoute
  ImportPspRoute: typeof ImportPspRoute
  ImportTravauxRoute: typeof ImportTravauxRoute
  PspValidationRoute: typeof PspValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adresses': {
      id: '/adresses'
      path: '/adresses'
      fullPath: '/adresses'
      preLoaderRoute: typeof AdressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-travaux': {
      id: '/dashboard-travaux'
      path: '/dashboard-travaux'
      fullPath: '/dashboard-travaux'
      preLoaderRoute: typeof DashboardTravauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-psp': {
      id: '/import-psp'
      path: '/import-psp'
      fullPath: '/import-psp'
      preLoaderRoute: typeof ImportPspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-travaux': {
      id: '/import-travaux'
      path: '/import-travaux'
      fullPath: '/import-travaux'
      preLoaderRoute: typeof ImportTravauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psp-validation': {
      id: '/psp-validation'
      path: '/psp-validation'
      fullPath: '/psp-validation'
      preLoaderRoute: typeof PspValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdressesRoute: AdressesRoute,
  DashboardTravauxRoute: DashboardTravauxRoute,
  ImportRoute: ImportRoute,
  ImportPspRoute: ImportPspRoute,
  ImportTravauxRoute: ImportTravauxRoute,
  PspValidationRoute: PspValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
